

title: Hortensia
name: Yuwei's Tech Blog
description: 
 I'm Yuwei Wu, now a master student at University of Pennsylvania majoring in systems engineering, interest in robotics, systems and optimization.
baseurl: ""
github_username:  yuwei-wu

baseurl: ""  # the subpath of your site, e.g. /blog

author: Yuwei WU
author_bio: I'm Yuwei Wu, now a master student at University of Pennsylvania majoring in systems engineering, interest in robotics, systems and optimization.


# social links
github_username:  yuwei-wu
linkedin_username: yuweiwu-36343214a


# wakatime username (coding activity)
wakatime_username: yuwei-wu


formspree_email: yuweiwu20001@outlook.com

footer-text: Copyright (c) 2020  Yuwei Wu 
# jekyll-paginate configuration
paginate: 10

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->
author: http://www.linkedin.com/in/alainpham

host: 0.0.0.0

