

title: Anhui ZHANG
name: Yanhui ZHANG's Tech Blog
description: 
 I'm Yanhui ZHANG, now a Research Assistant at Zhejiang University majoring in Aerospace Science and Technology engineering, interest in robotics, systems and optimization.
baseurl: ""
github_username:  ayan1991

baseurl: ""  # the subpath of your site, e.g. /blog

author: Yanhui ZHANG
author_bio:  I'm Yanhui ZHANG, now a Research Assistant at Zhejiang University majoring in Aerospace Science and Technology engineering, interest in aircraft, robotics, systems and optimization.


# social links
github_username:  ayan1991
linkedin_username: Yanhui ZHANG


# wakatime username (coding activity)
wakatime_username: Yanhui ZHANG


formspree_email: anhuizhang91@gmail.com

footer-text: Copyright (c) 2021  Yanhui ZHANG 
# jekyll-paginate configuration
paginate: 10

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->
author: https://orcid.org/0000-0003-0306-9540

host: 0.0.0.0

