# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'ZHANG Yanhui'

# ORC analytics
ORC-ID: 'https://orcid.org/0000-0003-0306-9540'



menu:
  - name: About
    link: /about
  - name: Blogs
    link: /blogs
  - name: Gallery
    submenu:
      - name: Autonmous systems
        link: /projects/RLV
        link: /projects/QuadCopter
        link: /projects/Coaxial twin-propeller UAV
        link: /projects/AutoParking
        link: /projects/Autonomous sailing vessel
      - name: SWARM
        link: /projects/Swarm Copter
        link: /projects/Swarm Birds
        link: /projects/Swarm Aircraft
      - name: AI-Image
        link: /projects/OCR
        link: /projects/Object Detection
        link: /projects/Obstacle avoidance
